### ISSUE TITLE
snpAnno

### ISSUE THREAD

**Issue by luciechanvillard** [chiaraherzog/IlluminaMouseMethylationmanifest#3]
Dear Chiara,

Thanks a lot for this! Very helpful :)

I was wondering if you have an idea how to perform the dropLociWithSnps function. I get an error that "The specificed 'snpAnno' is not supported by this function", I guess because there is no snpAnno file for mouse?

Thank you
Lucie

**Comment by chiaraherzog** [comment]
Hi Lucie,

thanks for your message! Yes, unfortunately as far as I know none of the probes for the mouse array have been specifically annotated to be SNPs, hence the functions that work for the human arrays that have been annotated in much more detail won't work here. Hopefully this may be added by Illumina in the future!
